import {
  ArrowUpDown,
  Bath,
  Bed,
  Bike,
  BookText,
  Building,
  Cable,
  ChefHat,
  Cigarette,
  Coffee,
  Facebook,
  Flower,
  HousePlug,
  Instagram,
  Lock,
  Mail,
  Mailbox,
  Map,
  MapPin,
  Microwave,
  PartyPopper,
  PencilRuler,
  Phone,
  Plug,
  Refrigerator,
  ShowerHead,
  Sofa,
  Sun,
  ThermometerSnowflake,
  Toilet,
  Tv,
  Utensils,
  UtensilsCrossed,
  WashingMachine,
  Wifi,
  Wind,
  type LucideIcon
} from 'lucide-react'

/**
 * Static icon map - only includes icons from allowedIcons.
 * Shared between frontend and Sanity Studio for tree-shaking.
 */
export const iconMap: Record<string, LucideIcon> = {
  'arrow-up-down': ArrowUpDown,
  bath: Bath,
  bed: Bed,
  bike: Bike,
  'book-text': BookText,
  building: Building,
  cable: Cable,
  'chef-hat': ChefHat,
  cigarette: Cigarette,
  coffee: Coffee,
  facebook: Facebook,
  flower: Flower,
  'house-plug': HousePlug,
  instagram: Instagram,
  lock: Lock,
  mail: Mail,
  mailbox: Mailbox,
  map: Map,
  'map-pin': MapPin,
  microwave: Microwave,
  'party-popper': PartyPopper,
  'pencil-ruler': PencilRuler,
  phone: Phone,
  plug: Plug,
  refrigerator: Refrigerator,
  'shower-head': ShowerHead,
  sofa: Sofa,
  sun: Sun,
  'thermometer-snowflake': ThermometerSnowflake,
  toilet: Toilet,
  tv: Tv,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  'washing-machine': WashingMachine,
  wifi: Wifi,
  wind: Wind
}
