// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "meta": {
    "siteName": "Share House Osaka",
    "siteDescription": "Founded in 1991. We have 3 share houses in the city of Osaka.",
    "siteShortName": "SHO"
  },
  "navigation": {
    "home": "Home",
    "shareHouses": "Share Houses",
    "contact": "Contact",
    "faq": "FAQ",
    "menu": "Menu",
    "toggleMenu": "Toggle Menu",
    "languageSelector": "Languages",
    "selectLanguage": "Select language"
  },
  "footer": { "company": "Animo Planning Co., Ltd." },
  "common": {
    "optional": "optional",
    "submit": "Submit",
    "reset": "Reset",
    "close": "Close",
    "showMore": "Show more",
    "showAllPhotos": "Show all photos",
    "charactersCounter": "{count} / {max} characters"
  },
  "home": {
    "heroTitle": "Vibrant <block>share house</block> community",
    "heroDescription": "Experience modern co-living in beautifully designed spaces. Connect with like-minded individuals while enjoying your own private room and shared common areas.",
    "heroCta": "Contact us",
    "housesTitle": "Our share houses",
    "housesDescription": "Three unique homes crafted for comfort, connection, and style in the heart of Osaka."
  },
  "houses": {
    "orange": {
      "name": "Orange House",
      "summary": "Relaxed spacious Japanese-style lounge",
      "caption": "Vibrant space designed for memorable experiences",
      "about": {
        "description": "Orange House is a private room accommodation located beside the Osaka city center. The house combines traditional Japanese styling with everyday conveniences, making it a calm base for longer stays in the Abeno area.",
        "highlights": {
          "privateKitchen": "Private rooms with kitchen (12 m²)",
          "longStay": "Long‑stay discounts available",
          "rooftopLounge": "Traditional rooftop lounge (100 m²) with Abeno Harukas views"
        }
      }
    },
    "apple": {
      "name": "Apple House",
      "summary": "Share house 8 minutes walk from Namba Station",
      "caption": "Experience the warmth and comfort with modern amenities",
      "about": {
        "description": "Apple House places residents within a one-minute walk of Daikokucho Station while keeping Namba in easy reach. Every private room includes a full bathroom and kitchen, delivering condo-like comfort for medium and long stays.",
        "highlights": {
          "privateKitchenBathroom": "Private rooms with kitchen and bathroom (11 m²)",
          "walkToNamba": "14 minutes walk to Namba",
          "loungeKitchen": "Lounge with a beautiful, fully equipped kitchen"
        }
      }
    },
    "lemon": {
      "name": "Lemon House",
      "summary": "Well-equipped private rooms and a luxurious lounge",
      "caption": "Bright and cheerful accommodation perfect for a refreshing stay",
      "about": {
        "description": "Lemon House offers private rooms and select dormitory options just moments from the heart of Namba. The compact building keeps an intimate feel while delivering everything needed for short and long-term stays.",
        "highlights": {
          "privateKitchensBathrooms": "Private rooms with kitchens and bathrooms (19 m²)",
          "spaciousRooms": "Spacious rooms, great for couples and friends",
          "communityLife": "Community life and international mingle in the center of Osaka"
        }
      }
    }
  },
  "houseSections": { "about": "About this place" },
  "houseLocation": {
    "heading": "Where you'll be",
    "highlights": {
      "orange": "Excellent access on the Subway Midosuji Line keeps you connected across Osaka.",
      "apple": "Walking distance to Namba and reach Daikokucho Station in just one minute.",
      "lemon": "Excellent access on the Subway Midosuji Line keeps you connected across Osaka."
    },
    "sections": {
      "gettingAround": "Getting around",
      "nearby": "What's nearby",
      "neighborhood": "Neighborhood"
    },
    "details": {
      "apple": {
        "stations": {
          "daikokucho": "Daikokucho Station (Subway Midosuji and Yotsubashi Lines), Exit 2 — about 1 minute on foot",
          "namba": "Namba Stations (various lines) — about 15 minutes on foot",
          "ebisucho": "Ebisucho Station — about 11 minutes on foot",
          "imamiya": "Imamiya Station / Imamiya-Ebisu — about 7 minutes on foot"
        },
        "nearby": {
          "supermarkets": "24-hour supermarket right next to the guest house and another large supermarket about 1 minute away",
          "sushi": "Conveyor belt sushi restaurant about 3 minutes on foot",
          "hundredYen": "¥100 shop by Daikokucho Station",
          "convenience": "Convenience store and post office about 3 minutes on foot"
        },
        "overview": "Only 1 minute walk from Daikokucho Station (Subway Midosuji Line, Yotsubashi Line). Just by a 24 hour open supermarket. Near 200 year old Kizu Market, and large public bath with hot stone spa. Walking distance from Namba, so you can enjoy the night life without worrying the last trains."
      },
      "lemon": {
        "stations": {
          "nihonbashi": "Nihonbashi Station (Subway Sakaisuji Line), Exit 10 — about 8 minutes on foot",
          "namba": "Namba Station (Subway Midosuji Line), Exit 4 — about 10 minutes on foot",
          "nankaiNamba": "Nankai Namba Station (South Exit) — about 8 minutes on foot"
        },
        "nearby": {
          "postOffice": "Post office about 2 minutes on foot",
          "supermarkets": "Supermarkets nearby at roughly 2, 4, and 6 minutes on foot",
          "discountShop": "Discount shop about 5 minutes on foot plus additional convenience stores within walking distance"
        },
        "overview": "Only 8 minutes walk to Namba! Great location, enjoy night life without worrying the last trains. Great access to anywhere in Osaka. Perfect for sightseeing or longer stay. No curfew."
      },
      "orange": {
        "stations": {
          "showacho": "Showacho Station (Subway Midosuji Line), Exit 2 — about 7 minutes on foot",
          "fuminosato": "Fuminosato Station (Subway Tanimachi Line), Exit 6 — about 3 minutes on foot",
          "tennoji": "Tennoji / Abenobashi — about 15 minutes on foot"
        },
        "nearby": {
          "supermarkets": "Supermarkets within about 5 minutes on foot",
          "showachoSupermarket": "Supermarket at Showacho Station",
          "harukas": "Abeno Harukas about 15 minutes on foot; Qs Mall about 12 minutes on foot"
        },
        "overview": "300m height! Only 15 minutes walk to the highest building in Japan “Abeno Harukas” Located near popular city attractions, with great public transportation to places like Osaka Castle, Osaka Aquarium Kaiyukan, Universal Studios Japan, Tsūtenkaku Tower. Only a few minutes walk to the nearest stations. Within walking distance, there are supermarkets, convenience stores, ¥100 shops, fitness center, bicycle shop and the ward office."
      }
    }
  },
  "houseDetails": {
    "rooms": "Rooms",
    "floors": "Floors",
    "minRent": "Min Rent"
  },
  "pricing": {
    "heading": "Pricing",
    "labels": {
      "rent": "Rent",
      "shortStay": "Short Stay",
      "dormitoryPlan": "Dormitory Plan",
      "otherFees": "Other Fees",
      "longStay": "Long Stay Discount"
    },
    "apple": {
      "rent": "¥50,000 ~ ¥70,000 per month (up to 2 people per room)",
      "shortStay": {
        "rate": "¥80,000 ~ ¥95,000 per month.",
        "allFees": "Stays under 3 months: All fees included.",
        "minimum": "Minimum stay: 1 month."
      },
      "longStay": "Discounts for 3-month and 6-month stays.",
      "otherFees": {
        "serviceFee": "Service fee: ¥10,000 per month",
        "utilities": "Utilities: About ¥3,000 per month (you pay what you use)",
        "deposit": "Deposit: ¥30,000 (returned when you leave, if no damage)"
      }
    },
    "lemon": {
      "rent": "¥50,000 ~ ¥70,000 per month (up to 2 people per room)",
      "shortStay": {
        "rate": "¥80,000 ~ ¥95,000 per month.",
        "allFees": "Stays under 3 months: All fees included.",
        "minimum": "Minimum stay: 1 month."
      },
      "dormitory": {
        "rate": "¥45,000 per month (includes utilities and service fee)",
        "details": "Co-ed, 3 beds per room, shared bathroom and kitchen.",
        "minimum": "Minimum stay: 1 month."
      },
      "longStay": "Discounts for 3-month and 6-month stays.",
      "otherFees": {
        "serviceFee": "Service fee: ¥10,000 per month",
        "utilities": "Utilities: About ¥3,000 per month (you pay what you use)",
        "deposit": "Deposit: ¥30,000 (returned when you leave, if no damage)",
        "washingMachine": "Washing machine: Free (on rooftop)",
        "dryer": "Dryer: ¥100 per 20 minutes"
      }
    },
    "orange": {
      "rent": {
        "base": "¥40,000 ~ ¥48,000 per month (1 person)",
        "secondPerson": "+¥5,000 per month for second person"
      },
      "longStay": {
        "secondMonth": "2nd month: Save ¥1,000",
        "thirdMonth": "3rd month: Save ¥2,000",
        "afterSixMonths": "After 6 months: Save ¥5,000 every month"
      },
      "otherFees": {
        "serviceFee": "Service fee: ¥12,000 per month",
        "utilities": "Utilities: About ¥3,000 ~ ¥4,000 per month (you pay what you use)",
        "washingMachine": "Washing machine: Free",
        "dryer": "Dryer: ¥100",
        "deposit": "Deposit: ¥30,000 (returned when you leave, if no damage)"
      }
    }
  },
  "amenities": {
    "heading": "What this place offers",
    "showAll": "Show all {count} amenities",
    "categories": {
      "internetClimate": "Internet & climate",
      "kitchenDining": "Kitchen & dining",
      "bathroom": "Bathroom",
      "laundry": "Laundry",
      "accommodation": "Accommodation",
      "commonAreas": "Common areas",
      "buildingAccess": "Building & access"
    },
    "notes": { "private": "Private", "shared": "Shared", "coin": "Coin" },
    "items": {
      "freeWifi": "Free Wi-Fi",
      "airConditioningHeating": "Air conditioning & heating",
      "kitchen": "Kitchen",
      "refrigerator": "Refrigerator",
      "microwaveToaster": "Microwave & toaster",
      "loungeKitchenOven": "Lounge kitchen with oven",
      "largeRefrigerator": "Large refrigerator",
      "bathroomWithShowerBathtub": "Bathroom with shower & bathtub",
      "washletToilet": "Washlet toilet",
      "washingMachine": "Washing machine",
      "dryingSpace": "Drying space",
      "furnishedRooms": "Fully furnished rooms ({size} m²)",
      "lounge": "Lounge",
      "tvEntertainment": "TV with Netflix, Blu-ray, cable",
      "elevator": "Elevator",
      "mailbox": "Mailbox",
      "bicycleParking": "Bicycle parking",
      "microwaveToasterRiceCooker": "Microwave, toaster & rice cooker",
      "tableware": "Tableware",
      "spaciousRooms": "Spacious rooms (19 m²)",
      "secureEntry": "Secure entry",
      "refrigeratorFreezer": "Refrigerator & freezer",
      "shower": "Shower",
      "dryer": "Dryer",
      "rooftopLounge": "Rooftop lounge (100 m²)",
      "coffeeTeaCorner": "Coffee & tea corner",
      "monthlyParties": "Monthly parties",
      "appliances": "Appliances (vacuum, iron)"
    }
  },
  "gallery": {
    "modalTitle": "Home Gallery",
    "explorePhotos": "Explore photos of {title}",
    "close": "Close gallery",
    "noImages": "No images found",
    "categories": {
      "room": "Room",
      "commonSpaces": "Common Spaces",
      "facilities": "Facilities",
      "buildingFeatures": "Building Features",
      "neighborhood": "Neighborhood",
      "floorPlan": "Floor Plan",
      "maps": "Maps"
    }
  },
  "contact": {
    "title": "Get in touch",
    "description": "Get in touch with us for any inquiries or questions.",
    "intro": "We're here to help! Choose the option that best describes your inquiry and we'll get back to you as soon as possible.",
    "nav": {
      "tour": "Tour request",
      "moveIn": "Move in request",
      "general": "General inquiry"
    },
    "cards": {
      "tourDescription": "Schedule a visit to see our share houses and get a feel for what we offer.",
      "moveInDescription": "Ready to move in? Share your preferences and timeline.",
      "generalDescription": "Questions about rooms, pricing, or availability? We’re happy to help."
    }
  },
  "faq": {
    "title": "FAQ",
    "description": "Find answers to common questions about our share houses.",
    "heading": "Frequently asked questions",
    "intro": "Here you'll find the key information to make the most of your stay. If you don't see your question here, please contact us by phone or email.",
    "qa": {
      "roomOccupancy": {
        "question": "Up to how many people can stay in a room?",
        "answer": "All houses accommodate up to 2 guests per room."
      },
      "rentDueDate": {
        "question": "When do I need to pay the rent every month?",
        "answer": "<strong>Orange House</strong> rent is due by the 10th of each month, while <strong>Lemon House</strong> and <strong>Apple House</strong> pay on the calendar day that matches their move-in date. For example, if you move in on the 23rd, rent is due every 23rd."
      },
      "managerInResidence": {
        "question": "Is there a manager in residence?",
        "answer": "<strong>Orange House</strong> has an on-site manager, while <strong>Lemon House</strong> and <strong>Apple House</strong> do not."
      },
      "moveInRequirements": {
        "question": "What do I need when I move in?",
        "answer": "Each house requires you to bring consumables and a valid ID."
      },
      "curfew": {
        "question": "Is there a curfew?",
        "answer": "There is no curfew in any house; please keep noise low in the early mornings and late evenings."
      },
      "floorsAndRooms": {
        "question": "How many floors and rooms?",
        "format": "{floors}-story building with {rooms} rooms."
      },
      "extraCosts": { "question": "What extra costs are there besides rent?" }
    },
    "costs": {
      "deposit": "Deposit",
      "commonFees": "Common fees",
      "utilityFees": "Utility fees",
      "waterBill": "Water bill",
      "laundromat": "Laundromat",
      "dryingMachine": "Drying machine",
      "internet": "Internet",
      "pricePerMonth": "¥{price}/month",
      "seasonalRates": {
        "summerWinter": "Summer/Winter: ¥{min}-¥{max}",
        "springAutumn": "Spring/Autumn: ¥{min}-¥{max}"
      },
      "pricePerMinutes": "¥{price}/{minutes}min",
      "free": "Free",
      "freeWifiLan": "Free Wi-Fi/LAN",
      "freeWifi": "Free Wi-Fi",
      "privateWasher": "Each room has a private washing machine.",
      "dash": "–"
    },
    "contact": {
      "withinJapan": "Within Japan",
      "fromOverseas": "From overseas",
      "phones": {
        "orange": {
          "domestic": "06-6627-0790",
          "international": "+81-6-6627-0790"
        },
        "apple": {
          "domestic": "06-6131-6677",
          "international": "+81-6-6131-6677"
        },
        "lemon": {
          "domestic": "06-6627-0790",
          "international": "+81-6-6627-0790"
        }
      }
    },
    "card": {
      "title": "Still have questions?",
      "description": "Have questions or need assistance? Our team is here to help!"
    }
  },
  "forms": {
    "status": {
      "sending": "Sending message...",
      "success": "Message sent successfully!",
      "failure": "Failed to send message.",
      "successDescription": "Thank you for contacting us {name}. We will get back to you shortly.",
      "errorDescription": "Please try again later or contact us directly at {email}."
    },
    "fields": {
      "gender": {
        "label": "Gender",
        "placeholder": "Select your gender",
        "description": "What is your gender?",
        "male": "Male",
        "female": "Female"
      },
      "name": {
        "label": "Name",
        "placeholder": "Enter your name",
        "description": "How should we address you?"
      },
      "age": {
        "label": "Age",
        "placeholder": "Enter your age",
        "description": "How old are you?"
      },
      "nationality": {
        "label": "Nationality",
        "placeholder": "Japanese",
        "description": "Let us know your nationality."
      },
      "email": {
        "label": "Email",
        "placeholder": "Enter your email",
        "description": "We'll use this email to share with you more details."
      },
      "phone": {
        "label": "Phone",
        "placeholder": "070-1234-5678",
        "description": "We may use this number to contact you on the visit day.",
        "optional": "(optional)"
      },
      "places": { "label": "Places" },
      "message": {
        "label": "Message",
        "contactPlaceholder": "Let us know any additional information or questions.",
        "moveInPlaceholder": "Share any special requirements for your move-in or questions you might have.",
        "description": "Do not include sensitive information such as your home address or credit card number."
      },
      "privacyPolicyAgreement": "By submitting this form, you agree to the <link>Privacy Policy</link>."
    },
    "contactForm": {
      "title": "General inquiry",
      "description": "Have questions about our services, pricing, or anything else? We're here to help."
    },
    "moveInForm": {
      "title": "Move in request",
      "description": "Ready to become a resident? Let us know your preferences and timeline.",
      "placesDescription": "Which places would you like to move in?",
      "moveInDateLabel": "Move-in date",
      "moveInDateDescription": "When would you like to move in?",
      "lengthOfStayLabel": "Length of stay",
      "lengthOfStayDescription": "How long would you like to stay?",
      "lengthOfStayPlaceholder": "Choose a duration",
      "durations": {
        "oneMonth": "1 month or more",
        "threeMonths": "3 months or more",
        "longTerm": "Long term"
      }
    },
    "tourForm": {
      "title": "Tour request",
      "description": "Schedule a visit to see our share houses and get a feel for what we offer.",
      "placesDescription": "Which places would you like to get a tour?",
      "tourDateLabel": "Tour date",
      "tourDateDescription": "When would you like to get a tour?",
      "tourHourLabel": "Tour hour",
      "tourHourDescription": "Our operating hours are from 10AM to 8PM."
    },
    "validation": {
      "placesMin": "Please select at least one share house.",
      "placesMax": "You can select up to 3 share houses.",
      "nameMin": "Name must be at least 2 characters long.",
      "agePositive": "Age must be a positive number.",
      "genderRequired": "Please select your gender.",
      "nationalityRequired": "Please enter your nationality.",
      "nationalityMax": "Nationality must be at most 100 characters.",
      "email": "Invalid email address.",
      "phone": "Invalid phone number",
      "messageMax": "Message must be at most 3000 characters.",
      "dateFuture": "Date must be today or later.",
      "privacyPolicy": "You must agree to the privacy policy.",
      "stayDuration": "Please select your desired minimum stay.",
      "timeRange": "Time must be between 10:00 and 20:00.",
      "messageMin": "Message must be at least 5 characters long."
    }
  },
  "errors": {
    "notFound": {
      "title": "Oops!",
      "description": "The page you're looking for isn't found, we suggest you back to home.",
      "contactSupport": "Need help? <link>Contact support</link>.",
      "backToHome": "Back to home page"
    }
  },
  "legal": {
    "privacy": {
      "title": "Privacy Policy",
      "lastUpdated": "Last updated: November 2025",
      "intro": {
        "company": "Animo Kikaku Co., Ltd. (“the Company”, “we”, “our”, or “us”) respects your privacy and is committed to protecting your personal information.",
        "purpose": "This Privacy Policy explains how we collect, use, store, and protect the information you provide through the contact forms and other features on this website (“the Service”)."
      },
      "sections": {
        "informationCollected": {
          "title": "1. Information We Collect",
          "paragraphs": [
            "When you contact us through the Service, we may collect the following personal information:"
          ],
          "list": [
            "Basic details: your name, age, gender, nationality, email address, and (optionally) telephone number",
            "Inquiry details: message content, questions, and form submission data",
            "Accommodation details: preferred tour dates, move-in dates, and housing preferences"
          ],
          "closing": "We collect this information directly from you when you submit a form or communicate with us."
        },
        "usage": {
          "title": "2. How We Use Your Information",
          "paragraphs": [
            "We use your personal information only for legitimate business purposes, including:"
          ],
          "list": [
            "Responding to your inquiries or requests",
            "Arranging property tours and managing move-in procedures",
            "Providing information, updates, and support related to the Service",
            "Maintaining internal records necessary for business operations and compliance"
          ],
          "closing": "We do not use your information for marketing purposes without your explicit consent."
        },
        "retention": {
          "title": "3. Retention Period",
          "paragraphs": [
            "We retain your personal information only as long as necessary to fulfill the purposes described above.",
            "Generally, this means up to 10 years after your business relationship with us ends.",
            "After this period, the information will be securely deleted or anonymized."
          ]
        },
        "sharing": {
          "title": "4. Sharing and International Transfers",
          "paragraphs": [
            "We do not share or sell your personal information to third parties.",
            "Your data will not be transferred outside Japan without your consent, unless required by law or necessary to protect legal rights in accordance with the Act on the Protection of Personal Information (APPI) and other applicable regulations."
          ]
        },
        "rights": {
          "title": "5. Your Rights",
          "paragraphs": ["You have the right to:"],
          "list": [
            "Request access to the personal information we hold about you",
            "Request correction, addition, or deletion of inaccurate or outdated information",
            "Withdraw your consent to the processing of your information (where applicable)"
          ],
          "closing": "We will respond promptly and transparently to all legitimate requests in accordance with Japanese privacy law."
        },
        "security": {
          "title": "6. Security Measures",
          "paragraphs": [
            "We take appropriate technical and organizational measures to protect your personal information against unauthorized access, loss, misuse, alteration, or disclosure.",
            "Access to personal data is restricted to authorized personnel only."
          ]
        },
        "contact": {
          "title": "7. Contact Us",
          "paragraphs": [
            "If you have any questions, concerns, or requests regarding this Privacy Policy or our data handling practices, please contact us at:"
          ],
          "details": [
            "Animo Kikaku Co., Ltd.",
            "1-21-21 Hannancho, Abeno-ku, Osaka, Japan",
            "📧 orange@guesthouseosaka.com",
            "👤 Representative Director: Kenji Hisamoto"
          ]
        },
        "changes": {
          "title": "8. Changes to This Policy",
          "paragraphs": [
            "We may update this Privacy Policy from time to time.",
            "Any significant changes will be announced on this page, with the updated date clearly indicated."
          ]
        }
      }
    }
  }
};
export default messages;