import type { StegaBranded, StegaCleaned } from 'next-sanity'

/**
 * Accepts both the clean TypeGen shape and the stega-branded shape that
 * `sanityFetch` returns when stega encoding may be enabled.
 *
 * `next-sanity@13.3` types `sanityFetch` data as `StegaBranded<...>`, so strings
 * that can carry stega payloads are no longer assignable to literal unions
 * generated by TypeGen. Components keep rendering those strings as-is (cleaning
 * them wholesale would strip the characters Visual Editing relies on) and use
 * `stegaClean` on the individual values they compare against string literals.
 *
 * Mirrors the internal `StegaAware` helper `next-sanity` uses for its
 * stega-aware `PortableText` types, which it does not export.
 */
export type StegaAware<T> = StegaCleaned<T> | StegaBranded<T>
