import type { ImageWithProps } from './storage'

export type ImageWithAlt = ImageWithProps & { alt: string }

/**
 * Image label keys mapped to their translation keys
 */
export const IMAGE_LABEL_KEYS: Record<string | number, string> = {
  1: 'apple.room.wood_flooring',
  4: 'apple.room.toilet_shower_and_bathtub',
  6: 'apple.room.kitchens',
  7: 'apple.room.washing_machine_in_balcony',
  8: 'apple.common-spaces.rooftop',
  11: 'apple.common-spaces.apple_tv_and_satellite_channels',
  12: 'apple.common-spaces.gas_cookers_available',
  14: 'apple.common-spaces.toilet_with_washlet_in_lounge',
  17: 'apple.building-features.elevator_for_heavy_luggages',
  18: 'apple.building-features.bicycle_parking_space',
  19: 'apple.building-features.mailbox_at_entrance',
  21: 'apple.building-features.view_from_rooftop_balcony',
  25: 'apple.neighborhood.hour_open_supermarket',
  26: 'apple.neighborhood.minute_walk_to_another_supermarket',
  27: 'apple.neighborhood.minutes_walk_to_rotating_sushi_restaurant',
  28: 'apple.neighborhood.shop_just_by_daikokucho_station',
  29: 'apple.neighborhood.minutes_walk_to_convenience_store',
  30: 'apple.neighborhood.minutes_walk_to_post_office',
  31: 'apple.neighborhood.namba_parks',
  33: 'apple.floor-plan.apple_house_floor_plan',
  34: 'lemon.maps.route_map',
  42: 'lemon.room.free_to_use_all_tablewares',
  43: 'lemon.room.ac_and_gas_heater',
  45: 'lemon.room.bathroom_with_sink_toilet_shower_and_bathtub',
  46: 'lemon.room.kitchen_with_dishes_cutlery_cups_and_kitchenware',
  47: 'lemon.common-spaces.story_building_with_rooms',
  50: 'lemon.common-spaces.laundromat',
  51: 'lemon.common-spaces.rooftop',
  52: 'lemon.neighborhood.minute_walk_from_nihonbashi_station_exit',
  53: 'lemon.neighborhood.minutes_walk_to_post_office',
  55: 'lemon.neighborhood.minutes_walk_to_supermarket',
  56: 'lemon.neighborhood.minutes_walk_to_another_supermarket',
  57: 'lemon.neighborhood.minutes_walk_to_discount_shop',
  60: 'lemon.neighborhood.minute_walk_to_another_supermarket',
  64: 'lemon.neighborhood.walking_distance_to_doguyasuji',
  67: 'lemon.neighborhood.nankai_namba_station',
  72: 'lemon.floor-plan.lemon_house_floor_plan',
  73: 'orange.maps.route_map',
  74: 'orange.room.all_rooms_set_in_traditional_japanese_style',
  82: 'orange.room.each_room_has_water_and_gas',
  84: 'orange.room.closet_as_desk_with_lamp_bookshelf_and_outlets',
  85: 'orange.common-spaces.traditional_japanese_style_lounge',
  86: 'orange.common-spaces.tv_show_by_abc',
  89: 'orange.common-spaces.lounge_equipped_with_large_air_conditioner',
  90: 'orange.common-spaces.large_collection_of_complete_comic_sets',
  91: 'orange.common-spaces.party_at_lounge_about_every_month',
  94: 'orange.common-spaces.coffee_tea_and_japanese_tea_available',
  104: 'orange.building-features.see_abeno_harukas_from_rooftop',
  105: 'orange.building-features.showacho_traditional_area',
  110: 'orange.neighborhood.supermarket_nearby_only_minutes_walk',
  111: 'orange.neighborhood.supermarket_by_showacho_station',
  114: 'orange.neighborhood.stylish_stores_behind_station',
  116: 'orange.neighborhood.minutes_walk_to_abeno_harukas',
  120: 'orange.neighborhood.minutes_walk_to_biggest_shopping_mall',
  121: 'orange.neighborhood.hanami_cherry_blossom_festival',
  123: 'orange.floor-plan.orange_house_floor_plan',
  124: 'orange.facilities.shower_room_behind_curtain',
  126: 'orange.facilities.shower_available_hours_for_free',
  129: 'orange.facilities.equipped_with_washlet'
}
